

services:
  # Ứng dụng ZenTask (PHP + Apache)
  app:
    build: .
    ports:
      - "8088:80"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=14122005
      - DB_NAME=todolist
    depends_on:
      - db
    networks:
      - zentask-network

  # Cơ sở dữ liệu MySQL (Tự khởi tạo dữ liệu bên trong)
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 14122005
      MYSQL_DATABASE: todolist
    ports:
      - "3307:3306"
    networks:
      - zentask-network

networks:
  zentask-network:
    driver: bridge
